# -*- coding: utf-8 -*-
"""Numpy_ and_Image_basics .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19veTRmi_HdlPjyAzWMYIaWyTPU-9nlYR
"""

