# -*- coding: utf-8 -*-
"""3-image_and_basics_with_openCV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cMLBff-1eQ1NXI0fiqvlvpsbuWhDCxom
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np 
import matplotlib.pyplot as plt
# %matplotlib inline 
import cv2

img = cv2.imread("/content/drive/MyDrive/dataset/train/without_mask/0.jpg")

type(img)

img

img.shape

plt.imshow(img)

# Matplotlib--> RGB Red Green Blue
# but opencV --> Blue Green Red
# we have to convert

fix_img= cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
plt.imshow(fix_img)

img_gray = cv2.imread("/content/drive/MyDrive/dataset/train/without_mask/0.jpg",cv2.IMREAD_GRAYSCALE)
plt.imshow(img_gray)

plt.imshow(img_gray,cmap='gray')

plt.imshow(fix_img)

fix_img.shape

new_img= cv2.resize(fix_img,(300,300))
cv2.imshow(new_img)

new_img = cv2.flip(fix_img,-1)
plt.imshow(new_img)

type(fix_img)

cv2.imwrite('totally_new.jpg',fix_img)

fig = plt.figure(figsize=(2,2))
ax = fig.add_subplot(111)
ax.imshow(fix_img)

"""## opening image files with OpenCV """

import cv2

img = cv2.imread("/content/drive/MyDrive/dataset/train/without_mask/0.jpg")
cv2.imshow("pic",img)
cv2.waitKey()







